# Generated by Django 5.2 on 2025-06-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pin",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pin",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pin",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pins/"),
        ),
    ]
