# Generated by Django 5.2.2 on 2025-06-16 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0002_pinlike_alter_pin_likes_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin_likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pinlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pinlike',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='pinlike',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='pins_commen_pin_id_0851bf_idx',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='source_url',
        ),
        migrations.AddField(
            model_name='pin',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pin_likes',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pins.pin'),
        ),
        migrations.AddField(
            model_name='pin_likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pin',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_pins', through='pins.Pin_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PinLike',
        ),
        migrations.AlterUniqueTogether(
            name='pin_likes',
            unique_together={('pin', 'user')},
        ),
    ]
