# Generated by Django 5.2 on 2025-06-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pins", "0002_pin_description_pin_image_url_alter_pin_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pin",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
