# Generated by Django 5.2.2 on 2025-06-16 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_pin_likes_alter_pinlike_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pin_likes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pin_likes',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='pin_likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pin',
            name='source_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pin',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['pin', 'created_at'], name='pins_commen_pin_id_0851bf_idx'),
        ),
        migrations.AddField(
            model_name='pinlike',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_likes', to='pins.pin'),
        ),
        migrations.AddField(
            model_name='pinlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pin',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_pins', through='pins.PinLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pin_likes',
        ),
        migrations.AddIndex(
            model_name='pinlike',
            index=models.Index(fields=['user', 'pin'], name='pins_pinlik_user_id_1934c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pinlike',
            unique_together={('pin', 'user')},
        ),
    ]
