# Generated by Django 5.2 on 2025-06-04 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pins", "0003_alter_pin_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pin",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
